"""Words the site speaker says. Fixed templates, never generated by a model:
a safety instruction must say exactly the same thing every time."""
from __future__ import annotations

TEMPLATES = {
    "day_start": {
        "hi": "नमस्ते। आज का काम अभी शुरू। पहले एक गिलास पानी पीजिए। हर बीस मिनट पर पानी पीते रहिए।",
        "en": "Good morning. Work starts now. Drink a glass of water first, then one every twenty minutes.",
    },
    "rest": {
        "hi": "अब {minutes} मिनट आराम। छाँव में बैठिए और एक गिलास पानी पीजिए।",
        "en": "Rest for {minutes} minutes now. Sit in the shade and drink a glass of water.",
    },
    "work_start": {
        "hi": "आराम खत्म। अगले {minutes} मिनट काम कीजिए। पानी पीते रहिए।",
        "en": "Rest is over. Work for the next {minutes} minutes. Keep drinking water.",
    },
    "pause": {
        "hi": "धूप अब बहुत ख़तरनाक है। काम {until} बजे तक बंद। छाँव में आराम कीजिए, ORS या नमक-नींबू पानी पीजिए।",
        "en": "The heat is now dangerous. Work stops until {until}. Rest in the shade and drink ORS or salted lemon water.",
    },
    "resume": {
        "hi": "गर्मी थोड़ी कम हुई है। अब काम फिर शुरू। पहले एक गिलास पानी पीजिए।",
        "en": "The heat has eased. Work starts again now. Drink a glass of water first.",
    },
    "day_end": {
        "hi": "आज का काम खत्म। घर पर भी पानी पीते रहिए। किसी को चक्कर, उल्टी या तेज़ सिरदर्द हो तो तुरंत सुपरवाइज़र को बताइए।",
        "en": "Work is over for today. Keep drinking water at home. Anyone dizzy, vomiting or with a bad headache must tell the supervisor now.",
    },
    "test": {
        "hi": "यह छाँव की जाँच घोषणा है। अगला ब्रेक समय पर बताया जाएगा।",
        "en": "This is a Chhaon test announcement. The next break will be announced on time.",
    },
}

LANGS = ("hi", "en")


def text_for(event: dict, lang: str) -> str:
    lang = lang if lang in LANGS else "hi"
    tpl = TEMPLATES[event["kind"]][lang]
    return tpl.format(minutes=event.get("minutes", ""), until=event.get("until", ""))
