"""Write web/protocol.js from backend/chhaon/protocol.py, so first aid works on the phone
with no network. Run after changing protocol.py; a unit test checks the two match."""
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))
from chhaon import protocol  # noqa: E402

DATA = {
    "red": list(protocol.RED_FLAGS),
    "amber": list(protocol.AMBER),
    "yellow": list(protocol.YELLOW),
    "green": list(protocol.GREEN),
    "steps": protocol.STEPS,
    "titles": protocol.TITLES,
    "source": "National Action Plan on Heat Related Illnesses, NCDC / MoHFW",
}

JS = f"""// Generated by scripts/gen_protocol_js.py from backend/chhaon/protocol.py. Do not edit.
// The same triage and first-aid steps as the server, so the phone can show them offline.
export const PROTOCOL = {json.dumps(DATA, ensure_ascii=False, indent=1)};

export function classify(symptoms) {{
  const s = new Set(symptoms);
  for (const level of ["red", "amber", "yellow", "green"]) if (PROTOCOL[level].some((x) => s.has(x))) return level;
  return null;
}}

export function guidance(level, lang) {{
  const l = lang === "en" ? "en" : "hi";
  return {{ level, title: PROTOCOL.titles[level][l], steps: PROTOCOL.steps[level][l], call_108: level === "red", source: PROTOCOL.source }};
}}
"""

if __name__ == "__main__":
    (ROOT / "web" / "protocol.js").write_text(JS, encoding="utf-8")
    print("wrote web/protocol.js")
